# Application details
# spring.application.name=taskflow
# server.port=8080

server.port=${PORT}
# Database Configuration (PostgreSQL)
# spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
# spring.datasource.username=postgres
# spring.datasource.password=root

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configurations (512-bit secure random key represented as hex string)
jwt.secret=9a67413c24b94f1b8a531e21b8c0c45163351f0b00db50b73bc8bf6487e41bc2c300898516d2466bbd08ea6b39d107a6ec89f214227181c0022718ef231e3d3e
# 24 hours in milliseconds (86400000)
jwt.expiration=86400000
